apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "titanic-api.fullname" . }}
  labels:
    {{- include "titanic-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  strategy:
    {{- toYaml .Values.strategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "titanic-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "titanic-api.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "titanic-api.serviceAccountName" . }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        env:
        - name: FLASK_ENV
          value: {{ .Values.env.FLASK_ENV | quote }}
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.dbCredentials.name }}
              key: {{ .Values.secrets.dbCredentials.key }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 10 }}
