apiVersion: v1
kind: Service
metadata:
  name: titanic-api
  namespace: titanic-api-${ENVIRONMENT}
spec:
  type: LoadBalancer
  selector:
    app: titanic-api
  ports:
  - port: 80
    targetPort: 5000
